services:
  tor-bridge:
    build: .
    user: "100:101"  # استفاده از UID/GID واقعی
    volumes:
      - ./tor-data:/var/lib/tor
      - ./tor-logs:/var/log/tor
    ports:
      - "2096:2096"
      - "8443:8443"
