services:
  tor-bridge:
    build: .
    container_name: tor-bridge
    restart: unless-stopped
    user: "100:101"
    volumes:
      - ./tor-data:/var/lib/tor
      - ./tor-logs:/var/log/tor
    ports:
      - "2096:2096/tcp"
      - "8443:8443/tcp"
    environment:
      - TZ=Asia/Tehran
    security_opt:
      - no-new-privileges:true
