version: '3.8'
services:
  tor-bridge:
    container_name: tor-bridge
    build: .
    user: "100:101"
    volumes:
      - tor_data:/var/lib/tor
      - tor_logs:/var/log/tor
    ports:
      - "2096:2096"
      - "8443:8443"
      healthcheck:
      test: ["CMD", "tor", "--verify-config"]
      interval: 30s
      timeout: 10s
      retries: 3

    restart: unless-stopped

volumes:
  tor_data:
  tor_logs:
